# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.19.2
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: GitHub
convert_readme_fragments_to_markdown: false
generate_requirements_txt: false
github_check_license: false
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: false
include_wkhtmltopdf: false
odoo_test_flavor: Both
odoo_version: 12.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups: []
repo_description: Electronic Data Interchange modules
repo_name: Electronic Data Interchange modules
repo_slug: edi
repo_website: https://github.com/OCA/edi
