language: python
sudo: true 
cache:
  apt: true
  directories:
    - $HOME/.cache/pip

python:
  - "3.5"

addons:
  apt:
# only add the two lines below if you need wkhtmltopdf for your tests
    sources:
      - pov-wkhtmltopdf
#    Search your sources alias here:
#      https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow
      - python-simplejson
      - python-serial
      - python-yaml
#     Search your packages here:
#       https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
      - wkhtmltopdf  # only add if needed and check the before_install section below
      - libpoppler-cpp-dev

# set up an X server to run wkhtmltopdf.
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

env:
  global:
  - VERSION="11.0" TESTS="0" LINT_CHECK="0" MAKEPOT="0"

  matrix:
  - LINT_CHECK="1"
  - TESTS="1" ODOO_REPO="OCA/OCB" OPTIONS="--test-report-directory=/tmp"
  - TESTS="1" ODOO_REPO="odoo/odoo" OPTIONS="--test-report-directory=/tmp" MAKEPOT="1"


install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - pip install invoice2data
  # Invoice2data new requires a recent version of pdftotext from https://poppler.freedesktop.org/releases.html
  # and the version below doesn't work any more
  - wget -P /tmp http://public.akretion.com/pdftotext-3.04
  - sudo mv /tmp/pdftotext-3.04 /usr/local/bin/pdftotext
  - sudo chmod 755 /usr/local/bin/pdftotext
  - pip install PyPDF2  # needed for account_invoice*zugferd
  - pip install phonenumbers
  # - pip install pdftotext

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
