language: python
sudo: true
cache:
  apt: true
  directories:
    - $HOME/.cache/pip

python:
  - "3.5"

before_install:
  - sudo apt-get update
  - sudo apt-get install --yes build-essential libpoppler-cpp-dev pkg-config python-dev

addons:
  postgresql: "9.6"
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow
      - python-simplejson
      - python-serial
      - python-yaml
env:
  global:
  - VERSION="11.0" TESTS="0" LINT_CHECK="0" MAKEPOT="0"
  - WKHTMLTOPDF_VERSION="0.12.5"

  matrix:
  - LINT_CHECK="1"
  - TESTS="1" ODOO_REPO="OCA/OCB" OPTIONS="--test-report-directory=/tmp"
  - TESTS="1" ODOO_REPO="odoo/odoo" OPTIONS="--test-report-directory=/tmp" MAKEPOT="1"


install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - pip install invoice2data
  - pip install pdftotext
  # Invoice2data new requires a recent version of pdftotext from https://poppler.freedesktop.org/releases.html
  # and the version below doesn't work any more
  - wget -P /tmp http://public.akretion.com/pdftotext-3.04
  - sudo mv /tmp/pdftotext-3.04 /usr/local/bin/pdftotext
  - sudo chmod 755 /usr/local/bin/pdftotext

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
