[project]
name = "odoo-addons-oca-edi"
version = "19.0.20260420.4"
dependencies = [
    "odoo-addon-base_business_document_import==19.0.*",
    "odoo-addon-base_edi==19.0.*",
    "odoo-addon-base_ubl==19.0.*",
    "odoo-addon-base_ubl_generate==19.0.*",
    "odoo-addon-base_ubl_parse==19.0.*",
    "odoo-addon-partner_identification_import==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
