import setuptools

with open('VERSION.txt', 'r') as f:
    version = f.read().strip()

setuptools.setup(
    name="odoo-addons-oca-edi",
    description="Meta package for oca-edi Odoo addons",
    version=version,
    install_requires=[
        'odoo-addon-account_edi_no_autocreate_partner>=16.0dev,<16.1dev',
        'odoo-addon-account_edi_no_product_name_match>=16.0dev,<16.1dev',
        'odoo-addon-account_edi_retrieve_partner>=16.0dev,<16.1dev',
        'odoo-addon-account_edi_ubl_cii_additional_document>=16.0dev,<16.1dev',
        'odoo-addon-account_edi_ubl_cii_check_total>=16.0dev,<16.1dev',
        'odoo-addon-account_edi_ubl_cii_invoice_line_name_enhance>=16.0dev,<16.1dev',
        'odoo-addon-account_edi_ubl_cii_purchase_match>=16.0dev,<16.1dev',
        'odoo-addon-account_edi_ubl_cii_retrieve_tax>=16.0dev,<16.1dev',
        'odoo-addon-account_edi_ubl_cii_supplier_invoice_number>=16.0dev,<16.1dev',
        'odoo-addon-account_edi_ubl_move_line_uom_and_packaging_unece>=16.0dev,<16.1dev',
        'odoo-addon-account_einvoice_generate>=16.0dev,<16.1dev',
        'odoo-addon-account_invoice_download>=16.0dev,<16.1dev',
        'odoo-addon-account_invoice_download_ovh>=16.0dev,<16.1dev',
        'odoo-addon-account_invoice_edifact>=16.0dev,<16.1dev',
        'odoo-addon-account_invoice_export>=16.0dev,<16.1dev',
        'odoo-addon-account_invoice_export_job>=16.0dev,<16.1dev',
        'odoo-addon-account_invoice_facturx>=16.0dev,<16.1dev',
        'odoo-addon-account_invoice_facturx_py3o>=16.0dev,<16.1dev',
        'odoo-addon-account_invoice_import>=16.0dev,<16.1dev',
        'odoo-addon-account_invoice_import_facturx>=16.0dev,<16.1dev',
        'odoo-addon-account_invoice_import_simple_pdf>=16.0dev,<16.1dev',
        'odoo-addon-account_invoice_import_ubl>=16.0dev,<16.1dev',
        'odoo-addon-account_invoice_ubl>=16.0dev,<16.1dev',
        'odoo-addon-base_business_document_import>=16.0dev,<16.1dev',
        'odoo-addon-base_business_document_import_phone>=16.0dev,<16.1dev',
        'odoo-addon-base_ebill_payment_contract>=16.0dev,<16.1dev',
        'odoo-addon-base_edi>=16.0dev,<16.1dev',
        'odoo-addon-base_edifact>=16.0dev,<16.1dev',
        'odoo-addon-base_facturx>=16.0dev,<16.1dev',
        'odoo-addon-base_ubl>=16.0dev,<16.1dev',
        'odoo-addon-base_ubl_payment>=16.0dev,<16.1dev',
        'odoo-addon-base_wamas_ubl>=16.0dev,<16.1dev',
        'odoo-addon-despatch_advice_import>=16.0dev,<16.1dev',
        'odoo-addon-despatch_advice_import_ubl>=16.0dev,<16.1dev',
        'odoo-addon-pdf_helper>=16.0dev,<16.1dev',
        'odoo-addon-purchase_order_ubl>=16.0dev,<16.1dev',
        'odoo-addon-sale_order_import>=16.0dev,<16.1dev',
        'odoo-addon-sale_order_import_edifact>=16.0dev,<16.1dev',
    ],
    classifiers=[
        'Programming Language :: Python',
        'Framework :: Odoo',
        'Framework :: Odoo :: 16.0',
    ]
)
